# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["humble"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: "${{ matrix.docker_image }} (${{ matrix.ros_distribution }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - docker_image: ubuntu:24.04
            ros_distribution: jazzy
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Install documentation tool
        run: |
          sudo apt install -y python3-rosdoc2 rsync

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: 'humble'

      - name: Build documentation # This example project is built using rosdoc2 and outputs the result to the 'docs_output' folder.
        run: |
          LIST_PACKAGES=`ls . | grep visp`
          for PACKAGE in $LIST_PACKAGES; do rosdoc2 build --package-path $PACKAGE; done

      - name: Preparing landing page of GitHub pages
        run: |
          cp doc/index.html docs_output/index.html
          touch docs_output/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs_output # The folder the action should deploy.
